version: 2
updates:

  - package-ecosystem: nuget
    directory: /TeachingRecordSystem/
    schedule:
      interval: 'daily'
    groups:
      dotnet:
        patterns:
          - 'Microsoft.AspNetCore.*'
          - 'Microsoft.EntityFrameworkCore.*'
          - 'Microsoft.Extensions.*'
          - 'System.Net.Http.Json'
      dfe-analytics:
        patterns:
          - 'Dfe.Analytics.*'
      serilog:
        patterns:
          - 'Serilog.*'
      openiddict:
        patterns:
          - 'OpenIddict.*'
      hangfire:
        patterns:
          - 'Hangfire.*'

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: 'daily'
    labels:
    - "dependencies"
    - "github-actions"
    - "devops"

  - package-ecosystem: terraform
    directory: /terraform/
    schedule:
      interval: 'daily'
    labels:
    - "dependencies"
    - "terraform"
    - "devops"
