version: 2
updates:

  - package-ecosystem: nuget
    directory: /TeachingRecordSystem/
    schedule:
      interval: 'daily'
    groups:
      dotnet:
        patterns:
          - 'Microsoft.AspNetCore.*'
          - 'Microsoft.EntityFrameworkCore.*'
          - 'Microsoft.Extensions.*'
          - 'System.Net.Http.Json'
      serilog:
        patterns:
          - 'Serilog.*'
      openiddict:
        patterns:
          - 'OpenIddict.*'
      hangfire:
        patterns:
          - 'Hangfire.*'
      sentry:
        patterns:
          - 'Sentry.*'
      nsign:
        patterns:
          - 'NSign.*'

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: 'daily'

  - package-ecosystem: terraform
    directory: /terraform/
    schedule:
      interval: 'daily'
